name: Update README from template

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release metadata
        run: |
          VERSION="${GITHUB_REF_NAME}"
          VERSION="${VERSION#v}"
          DATE=$(date +'%Y-%m-%d')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "DATE=${DATE}" >> $GITHUB_ENV


      - name: Generate README.md from template
        run: |
          sed "s|{{VERSION}}|${VERSION}|g; s|{{DATE}}|${DATE}|g" README.template.md > README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: update README for release ${VERSION}" || echo "No changes to commit"
          git push
